variable "tfc_aws_dynamic_credentials" {
  description = "AWS dynamic credentials generated by HCP Terraform"
  type = object({
    default = object({
      shared_config_file = string
    })
    aliases = map(object({
      shared_config_file = string
    }))
  })
}

provider "aws" {
  region = var.aws_region

  shared_config_files = [
    var.tfc_aws_dynamic_credentials.default.shared_config_file
  ]
}